// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BeginFetchingWindows() {
  return window['go']['main']['App']['BeginFetchingWindows']();
}

export function GetWindows() {
  return window['go']['main']['App']['GetWindows']();
}

export function SetWindowTitle(arg1, arg2) {
  return window['go']['main']['App']['SetWindowTitle'](arg1, arg2);
}
