// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BeginFetchingWindows():Promise<void>;

export function GetWindows():Promise<Array<main.Window>>;

export function SetWindowTitle(arg1:number,arg2:string):Promise<void>;
